# Generated by Django 2.1.4 on 2019-05-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'ordering': ['game_name'],
            },
        ),
    ]
