# Generated by Django 2.1.4 on 2019-05-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'ordering': ['person_name'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='person',
            field=models.ManyToManyField(blank=True, default='', related_name='games', to='gamelist.Person'),
        ),
    ]
